theme: jekyll-theme-hacker
repository: matippetts/matippetts.github.io
title: Mark Tippetts
description: self-referential musings of a metaprogrammer

collections:
  microformats:
    output: true
  schema-dot-org:
    output: true
  ontologies:
    output: true

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-readme-index
  - jekyll-optional-front-matter
  