theme: jekyll-theme-hacker

collections:
  ideas:
    output: true
  projects:
    output: true
  methodologies:
    output: true
  architectures:
    output: true
  languages:
    output: true
  libraries:
    output: true
  platforms:
    output: true
  tools:
    output: true
  protocols:
    output: true
