repository: matippetts/matippetts.github.io
url: https://matippetts.github.io
title: Mark Tippetts
description: Self-referential musings of a metaprogrammer
author: Mark Tippetts
theme: jekyll-theme-hacker

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-readme-index
  - jekyll-optional-front-matter
  