backend:
  name: github
  repo: matippetts/matippetts.github.io
  branch: master
  site_domain: matippetts.netlify.com
  
publish_mode: editorial_workflow

media_folder: images

collections:
  # [name, label, file/folder, create/delete, slug, fields]
  # field: [ name, label, hint, pattern, required, widget ]
  # widgets: [ object, boolean, date, datetime, file, hidden, image, list, markdown, number, relation, select, string, text ]
  - name: employer
    label: Employer
    folder: _data/employers
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
  - name: client
    label: Client
    folder: _data/clients
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
  - name: certification
    label: Certification
    folder: _data/certifications
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
