backend:
  name: github
  repo: matippetts/matippetts.github.io
  branch: master

publish_mode: editorial_workflow

media_folder: images

collections:
  # [name, label, file/folder, create/delete, slug, fields]
  # field: [ name, label, hint, pattern, required, widget ]
  # widgets: [ object, boolean, date, datetime, file, hidden, image, list, markdown, number, relation, select, string, text ]
  - name: drafts
    label: Drafts
    folder: _drafts
    format: frontmatter
    extension: md
    create: true
    delete: false
    fields:
      - {name: "title", label: "Title", widget: "string"}
      - {name: "author", label: "Author", widget: "string", default: "Mark Tippetts"}
      - {name: "published", label: "Published", widget: "boolean", default: false}
      - {name: "tags", label: "Tags", widget: "list", required: false}
      - {name: "body", label: "Body", widget: "markdown"}
  - name: employer
    label: Employers
    folder: _employers
    create: true
    identifier_field: employer
    fields:
      - {name: "employer", label: "Employer", widget: "string"}
      - {name: "location", label: "Location", widget: "string"}
      - {name: "position", label: "Position", widget: "string"}
      - {name: "start", label: "From", widget: "date", format: "MMM YY"}
      - {name: "end", label: "To", widget: "date", format: "MMM YY"}
  - name: client
    label: Clients
    folder: _clients
    create: true
    identifier_field: name
    fields:
      - {name: "name", label: "Name", widget: "string"}
      - {name: "location", label: "Location", widget: "string"}
  - name: platform
    label: Platforms
    folder: _platforms
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
  - name: tool
    label: Tools
    folder: _tools
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
  - name: framework
    label: Frameworks
    folder: _frameworks
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
  - name: language
    label: Languages
    folder: _languages
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
  - name: pattern
    label: Patterns
    folder: _patterns
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
  - name: standard
    label: Standards
    folder: _standards
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
  - name: certification
    label: Certifications
    folder: _certifications
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
